### PR TITLE
Proper support of RequireJS config

### PR DESCRIPTION
**Pull request by kirill-konshin**
Fix for https://github.com/podio/requirejs-react-jsx/issues/9

### CODE REVIEW

**Comment by srn** [comment]
Great, thanks. I'm not really sure I want to keep the deprecated support around though, I think we should just remove it and let the user read the docs instead.

**Comment by Munter** [comment]
Just major version bump. Semver will tell people to watch out

**Comment by kirill-konshin** [comment]
Do you want me to remove it or you'll do it yourself when you'll bump a version?

**Comment by kirill-konshin** [comment]
So will this be merged?

**Comment by srn** [comment]
Thanks for the PR :ok_hand:

**Comment by kirill-konshin** [comment]
You are welcome :)

**Comment by srn** [comment]
Also published to npm: https://github.com/podio/requirejs-react-jsx/commit/8eaa0847cebd755341528cc0c73f6048cf5e8f44

**Comment by kirill-konshin** [comment]
Can you also update `bower.json`?

**Comment by Munter** [comment]
We're not updating version numbers in bower.json. Using git tags instead. But `v0.14.0` was missing. Fixed now

**Pull request merged**
