### PR TITLE
Proper support of RequireJS config for Build

### PR DESCRIPTION
**Pull request by kirill-konshin**
Forgotten piece for build procedure...

### CODE REVIEW

**Comment by Munter** [comment]
Thanks

**Comment by kirill-konshin** [comment]
No problem :)

**Comment by kirill-konshin** [comment]
Don't forget to create a new tag...

**Comment by Munter** [comment]
Done. v0.14.2 is out :)

**Comment by kirill-konshin** [comment]
Awesome!

**Pull request merged**
